services:
  downtimemonitor:
    build:
      context: .
    container_name: downtime-monitoring-backend
    ports:
      - "6100:6100"
    networks:
      - downTime-network
    env_file:
      - .env

networks:
  downTime-network:
    driver: bridge
